### ISSUE TITLE
Slight error with drive crank radius calculation

### ISSUE THREAD

**Issue by TheElementalOfCreation** [benbrandt22/genevaGen#7]
I don't know if this is even fixable, or if it is just an odd quirk with the language, but the drive crank radius is just the tiniest bit off. It doesn't really cause problems, and it might not even be worth fixing, but it is most obvious when you change it to a four position drive, with a radius of 1. It will end up giving you a drive crank radius of .999999999999998 or something very close to that.

**Comment by TheElementalOfCreation** [comment]
Great tool, by the way. It had been very helpful for me.

**Comment by benbrandt22** [comment]
Good catch. There is some slight error in precision when all of the math is done that's out of my control as far as I can tell. All the other values on the page are displayed and forced to no more than 4 digits after the decimal point. I'll update the a and b values to 4 digits and the rounding should give you more reasonable and expected values. In the case of your example, this will result in a radius of 0.9999999999999998 being displayed as 1.0000
